### ISSUE TITLE
support Android 6.0?

### ISSUE THREAD

**Issue by nyasukun** [SuppSandroB/sandrop#122]
I tried to build from this repository for Android 6.0 (Marshmallow) and got failure to build.
Since Android 6.0, Apache HTTP client is removed and this failure is related with this removal.

Do you have a plan to support Android 6.0+?

**Comment by SuppSandroB** [comment]
I think that is still there but not visible in android.jar if you state latest api.
So you should try to build with API level 19 for example.

**Comment by nyasukun** [comment]
yes. it seems ok to build.

I tried to use the app published from google play. then but ssl mitm does not seem works.
My phone: Nexus 5X android 6.0.1.

I also check in other version(android 4.4.4) and it works.

**Comment by SuppSandroB** [comment]
Must say that didn't test it for a while and I think that some user wrote that is something to change that it works on android 6.0. Creating socket different way maybe. Change must be on some fork or usage of code.
Will try to look at it soon and fix it.

**Comment by SuppSandroB** [comment]
https://github.com/SuppSandroB/sandrop/commit/e8ea22008ca4172017379a8cdd369870cfc7e69e
Try if it works for you.

**Comment by nyasukun** [comment]
It seems works on Nexus5x(Android 6.0.1).

**Comment by SuppSandroB** [comment]
Great! 
Version with this fix is already on Google Play.
Thank you for reporting. Makes app better for all.
I will close the issue.
