### ISSUE TITLE
Certificate issues on Nexus Player

### ISSUE THREAD

**Issue by tkanchin** [SuppSandroB/sandrop#124]
I've installed sandroproxy on my Nexus player. When I select "export to CA" option and type in the name of the certificate, I'm getting the toast message "certificate is not installed". I've even searched the /data/misc/keystore directory and I couldn't see any certificates. is there any workaround to install sandroproxy on Android TV?

**Comment by SuppSandroB** [comment]
On log tab there is line where is cert stored in sandroproxy, when you start it. You can try then manually to import it to cert store.

**Comment by tkanchin** [comment]
Thank you! I tried to do that but it's not working. I've imported the .keystoreca_export.crt file to keystore/user_0 directory and renamed it with 1000_CACERT_Sandroproxy, but that didn't work. Then I've extracted the hash and renamed the file with that hash and placed it in the keychain/cacerts-added/ directory but that didn't work too. I'm able to get things running on the phone but nexus player doesn't have the option to add certificates from GUI! Is there any other way to get things running on Nexus player?

**Comment by SuppSandroB** [comment]
Sandroproxy uses intent to store it. 
https://github.com/SuppSandroB/sandrop/blob/master/projects/SandroProxyPlugin/src/org/sandroproxy/plugin/gui/MainActivity.java#L360
Doesn't know how to do it on Nexus Player. Maybe on xda forum for can help you out.
http://forum.xda-developers.com/nexus-player

**Comment by tkanchin** [comment]
Okay! Thanks! I'll ask this on xda-developers forum!

**Comment by tkanchin** [comment]
Hi, sorry for the super late comment! Android TV doesn't have the CA cert store enabled by default! Thanks
