### ISSUE TITLE
Proxy for mobile data connection

### ISSUE THREAD

**Issue by andytorres** [SuppSandroB/sandrop#131]
Hi, is there a chance that Drony supports mobile data connections? I'm having a struggle with the case, I even rooted the device in order to use proxydroid, but it doesn't work for me.
I've been using Drony with my company's wifi, and it works like a charm. I would like to also use it for my mobile data connection.
Thanks in advance

**Comment by SuppSandroB** [comment]
You can. just put settinngs under Not Listed networks.

**Comment by b0riska** [comment]
Which settings?
