### ISSUE TITLE
Drony not working on Android 9, Pixel 2 for whatsapp

### ISSUE THREAD

**Issue by hmanupati** [SuppSandroB/sandrop#137]
Noticed that drony stopped working after android updated to 9. 

http and https seems working, but whatsapp stopped working, using squid proxy.

**Comment by SuppSandroB** [comment]
Will look at it. Can you maybe give more details from logcat what is happening. Currently don't have device to test it properly on android 9.

**Comment by hmanupati** [comment]
Its 204 error for apps but seems to be able to browse via browser, 
Please check below logs, 

`Not listening on 127.0.0.1:8020
Not listening on 127.0.0.1:8019
com.google.SSRestartDetector<->http://connectivitycheck.gstatic.com/generate_204 : 204 No Content
Google Services Framework<->ssl.google-analytics.com:443
Gmail<->inbox.google.com:443
Messenger<->graph.facebook.com:443
com.google.SSRestartDetector<->http://connectivitycheck.gstatic.com/generate_204 : 204 No Content
com.google.SSRestartDetector<->http://connectivitycheck.gstatic.com/generate_204 : 204 No Content
Google Services Framework<->googleads.g.doubleclick.net:443
Google Services Framework<->googleads.g.doubleclick.net:443
Google Services Framework<->googleads.g.doubleclick.net:443
Messenger<->http://portal.fb.com/mobile/status.php : 204 No Content
WhatsApp<->http://clients3.google.com/generate_204 : 204 No Content
WhatsApp<->http://clients3.google.com/generate_204 : 204 No Content
com.google.SSRestartDetector<->http://connectivitycheck.gstatic.com/generate_204 : 204 No Content
com.google.SSRestartDetector<->www.google.com:443
Facebook<->graph.facebook.com:443
Google Services Framework<->googleads.g.doubleclick.net:443
Google Services Framework<->googleads.g.doubleclick.net:443
Proxy listening on 127.0.0.1:8020
Proxy listening on 127.0.0.1:8019`

**Comment by SuppSandroB** [comment]
This looks like whatsapp is checking connection to internet.
There should be additional requests from whatsapp. Will try to test it on proper device with android 9.

**Comment by SuppSandroB** [comment]
There were quite a changes in version 9. Will try to make it work.
https://developer.android.com/about/versions/pie/android-9.0-changes-all

**Comment by hmanupati** [comment]
Thank you for prompt response, Please let me know if you need any assistance.

**Comment by SuppSandroB** [comment]
There is new version on Google Play. Please try if it works for you.

**Comment by hmanupati** [comment]
update is working for http(s) and apps on android pie 

Thank you

**Comment by brookhong** [comment]
After I upgraded to Android 9.0, the proxy set by Drony does not work with Google Play Store, though it works with Browser. Any ideas?
